// Automatically generated by flapigen
package com.nixalpha.rustapplication.lib;
import androidx.annotation.NonNull;

public final class Session {

    public Session(int a_num) {
        mNativeObj = init(a_num);
    }
    private static native long init(int a_num);

    public final int add_and1(int val) {
        int ret = do_add_and1(mNativeObj, val);

        return ret;
    }
    private static native int do_add_and1(long self, int val);

    public static native @NonNull String greet(@NonNull String to);

    public static native @NonNull String lspath(@NonNull String dir);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Session(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}